# Generated by Django 4.1.5 on 2023-01-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=200, verbose_name='Marks')),
                ('memes', models.CharField(max_length=250, verbose_name='Memes')),
                ('unique_id', models.CharField(max_length=10, verbose_name='ID')),
            ],
        ),
    ]
