# Generated by Django 4.1.5 on 2023-01-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name': 'Результат оценивания', 'verbose_name_plural': 'Результаты оценивания'},
        ),
    ]
